networks:
  net:
    driver: bridge

services:
  db:
    container_name: cpex-db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - ./docker/data/mongo:/data/db
    networks:
      - net

  sti-pki:
    container_name: cpex-sti-pki
    image: cpex
    command: uvicorn cpex.servers.sti_pki_server:app --host 0.0.0.0 --port 8888 --reload
    ports:
      - 8888:8888
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - net

  cps-0:
    container_name: cpex-cps-0
    image: cpex
    command: uvicorn cpex.servers.cps_server:app --host 0.0.0.0 --port 8888 --reload
    ports:
      - 10000:8888
    environment:
      - CPS_ID=0
      - CPS_PORT=10000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - net
