x-cpex-service: &cpex-service
  image: cpex
  platform: linux/x86_64
  volumes:
    - '.:/app'
  networks:
    - net
  depends_on:
    - cache

services:
  cache:
    container_name: sti-cache
    image: redis
    platform: linux/x86_64
    ports:
      - 6379:6379
    networks:
      - net

  atis-cps-0:
    <<: *cpex-service
    container_name: atis-cps-0
    command: > 
      gunicorn cpex.prototype.stirshaken.cps_server:app 
      --bind 0.0.0.0:80 
      --workers 2
      --worker-class uvicorn.workers.UvicornWorker 
      --reload
    ports:
      - 10433:80
    environment:
      - NODE_FQDN=atis-cps-0
      - NODE_PORT=10433

  atis-cps-1:
    <<: *cpex-service
    container_name: atis-cps-1
    command:  > 
      gunicorn cpex.prototype.stirshaken.cps_server:app 
      --bind 0.0.0.0:80 
      --workers 2
      --worker-class uvicorn.workers.UvicornWorker 
      --reload
    ports:
      - 10434:80
    environment:
      - NODE_FQDN=atis-cps-1
      - NODE_PORT=10434

networks:
  net:
    driver: bridge