x-cpex-service: &cpex-service
  image: cpex
  platform: linux/x86_64
  volumes:
    - '.:/app'
  depends_on:
    - cache
  networks:
    - net

services:
  experiment:
    image: cpex-experiment
    platform: linux/x86_64
    container_name: cpex-exp
    command: tail -f /dev/null
    environment:
      - DOCKER_SOCKET_PATH=${DOCKER_SOCKET_PATH:-/var/run/docker.sock}
      - HOST_APP_PATH=${HOST_APP_PATH}
    volumes:
      - '.:/app'
      - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
      - './docker/data/automation/.aws:/root/.aws'
      - './docker/data/automation/.ssh:/root/.ssh'
    depends_on:
      - cache
      - mongo
    networks:
      - net
    profiles: [experiment]

# CPeX Services
  evaluator:
    <<: *cpex-service
    container_name: evaluator
    command: > 
      gunicorn cpex.servers.evaluator:app 
      --bind 0.0.0.0:80 
      --workers 4
      --worker-class uvicorn.workers.UvicornWorker 
      --log-file=-
      --reload
    ports:
      - 10430:80
    profiles: [cpex]

  message-store:
    <<: *cpex-service
    container_name: message-store
    command: >
      gunicorn cpex.servers.message_store:app 
      --bind 0.0.0.0:80 
      --workers 4
      --worker-class uvicorn.workers.UvicornWorker 
      --log-file=-
      --reload
    ports:
      - 10431:80
    profiles: [cpex]

  iwf-proxy:
    <<: *cpex-service
    container_name: cpex-proxy
    command: >
      gunicorn cpex.servers.cpex_proxy:app 
      --bind 0.0.0.0:80 
      --workers 8
      --worker-class uvicorn.workers.UvicornWorker 
      --log-file=-
      --reload
    profiles: [proxy]

  sti-cps-0:
    <<: *cpex-service
    container_name: sti-cps-0
    command: > 
      gunicorn cpex.prototype.stirshaken.cps_server:app 
      --bind 0.0.0.0:80 
      --workers 4
      --worker-class uvicorn.workers.UvicornWorker 
      --log-file=-
      --timeout 0
      --reload
    ports:
      - 10433:80
    environment:
      - NODE_PORT=10433
    profiles: [atis]

  sti-cps-1:
    <<: *cpex-service
    container_name: sti-cps-1
    command:  > 
      gunicorn cpex.prototype.stirshaken.cps_server:app 
      --bind 0.0.0.0:80 
      --workers 4
      --worker-class uvicorn.workers.UvicornWorker 
      --log-file=-
      --timeout 0
      --reload
    ports:
      - 10434:80
    environment:
      - NODE_PORT=10434
    profiles: [atis]

# Cache and Database
  cache:
    container_name: cpex-cache
    image: redis
    platform: linux/x86_64
    ports:
      - 6379:6379
    networks:
      - net
  
  mongo:
    container_name: cpex-mongo
    image: mongo
    platform: linux/x86_64
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - ./docker/data/mongo:/data/db
    networks:
      - net

networks:
  net:
    driver: bridge