x-cpex-service: &cpex-service
  image: cpex
  platform: linux/x86_64
  volumes:
    - '.:/app'
  depends_on:
    - cache
  networks:
    - net

services:
  evaluator:
    <<: *cpex-service
    container_name: evaluator
    command: uvicorn cpex.servers.evaluator:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 10430:80

  message-store:
    <<: *cpex-service
    container_name: message-store
    command: uvicorn cpex.servers.message_store:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 10431:80

  cache:
    container_name: cpex-cache
    image: redis
    platform: linux/x86_64
    ports:
      - 6379:6379
    networks:
      - net

networks:
  net:
    driver: bridge