x-cpex-service: &cpex-service
  image: cpex
  platform: linux/x86_64
  volumes:
    - '.:/app'
  depends_on:
    - cache
  networks:
    - net

services:
# OPRF Servers
  oprf-s1:
    <<: *cpex-service
    container_name: oprf-s1
    command: uvicorn cpex.servers.oprf_server:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 9001:80

  oprf-s2:
    <<: *cpex-service
    container_name: oprf-s2
    command: uvicorn cpex.servers.oprf_server:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 9002:80

# Atis OOB Services
  sti-pki:
    <<: *cpex-service
    container_name: sti-pki
    command: uvicorn cpex.prototype.stirshaken.sti_pki_server:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8888:8888

# Experiment Runner
  experiment:
    <<: *cpex-service
    container_name: cpex-exp
    command: tail -f /dev/null

# Cache and Database
  cache:
    container_name: cpex-cache
    image: redis
    platform: linux/x86_64
    networks:
      - net

  mongo:
    container_name: cpex-mongo
    image: mongo
    platform: linux/x86_64
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - ./docker/data/mongo:/data/db
    networks:
      - net

networks:
  net:
    driver: bridge