x-cpex-service: &cpex-service
  image: cpex
  platform: linux/x86_64
  volumes:
    - '.:/app'
  depends_on:
    - cache
  networks:
    - net

services:
  evaluator:
    <<: *cpex-service
    container_name: evaluator
    command: > 
      gunicorn cpex.servers.evaluator:app 
      --bind 0.0.0.0:80 
      --workers 1
      --worker-class uvicorn.workers.UvicornWorker 
      --log-file=-
      --reload
    ports:
      - 10430:80

  message-store:
    <<: *cpex-service
    container_name: message-store
    command: >
      gunicorn cpex.servers.message_store:app 
      --bind 0.0.0.0:80 
      --workers 1
      --worker-class uvicorn.workers.UvicornWorker 
      --log-file=-
      --reload
    ports:
      - 10431:80

  atis-cps-0:
    <<: *cpex-service
    container_name: atis-cps-0
    command: > 
      gunicorn cpex.prototype.stirshaken.cps_server:app 
      --bind 0.0.0.0:80 
      --workers 1
      --worker-class uvicorn.workers.UvicornWorker 
      --log-file=-
      --reload
    ports:
      - 10433:80
    environment:
      - NODE_PORT=10433

  atis-cps-1:
    <<: *cpex-service
    container_name: atis-cps-1
    command:  > 
      gunicorn cpex.prototype.stirshaken.cps_server:app 
      --bind 0.0.0.0:80 
      --workers 1
      --worker-class uvicorn.workers.UvicornWorker 
      --log-file=-
      --reload
    ports:
      - 10434:80
    environment:
      - NODE_PORT=10434

  cache:
    container_name: cache-all
    image: redis
    platform: linux/x86_64
    ports:
      - 6379:6379
    networks:
      - net

networks:
  net:
    driver: bridge