x-cpex-service: &cpex-service
  image: cpex
  platform: linux/x86_64
  volumes:
    - '.:/app'
  networks:
    - net
  depends_on:
    - mongo
    - cache

services:
  mongo:
    container_name: sti-mongo
    image: mongo
    platform: linux/x86_64
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - ./docker/data/sti-mongo:/data/db
    networks:
      - net

  cache:
    container_name: sti-cache
    image: redis
    platform: linux/x86_64
    ports:
      - 6379:6379
    networks:
      - net
    
  sti-cr:
    <<: *cpex-service
    container_name: sti-cr
    command: uvicorn cpex.prototype.stirshaken.cert_repo:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 10321:80

  sti-cps:
    <<: *cpex-service
    container_name: sti-cps
    command: uvicorn cpex.prototype.stirshaken.cps_server:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 11321:80

networks:
  net:
    driver: bridge