services:
# Atis OOB Services
  cert-repo:
    image: cpex
    platform: linux/x86_64
    container_name: cert-repo
    command: uvicorn cpex.prototype.stirshaken.cert_repo:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8888:80
    volumes:
      - '.:/app'
    depends_on:
      - cache
    networks:
      - net

  mongo:
    container_name: cpex-mongo
    image: mongo
    platform: linux/x86_64
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - ./docker/data/mongo:/data/db
    networks:
      - net

networks:
  net:
    driver: bridge