services:
  oob_db:
    container_name: oob_db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - mongooob:/data/db

  ca:
    container_name: ca
    build:
      context: ./docker
      dockerfile: Dockerfile
    command: uvicorn server-ca:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8888:80
    volumes:
      - .:/app
    depends_on:
      - oob_db

  cps_1:
    container_name: cps_1
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - CPS_FQDN=localhost:7771
    command: uvicorn server-cps:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 7771:80
    volumes:
      - .:/app
    depends_on:
      - oob_db

  cps_2:
    container_name: cps_2
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - CPS_FQDN=localhost:7772
    command: uvicorn server-cps:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 7772:80
    volumes:
      - .:/app
    depends_on:
      - oob_db

  cps_3:
    container_name: cps_3
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - CPS_FQDN=localhost:7773
    command: uvicorn server-cps:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 7773:80
    volumes:
      - .:/app
    depends_on:
      - oob_db

  cps_4:
    container_name: cps_4
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - CPS_FQDN=localhost:7774
    command: uvicorn server-cps:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 7774:80
    volumes:
      - .:/app
    depends_on:
      - oob_db

  cps_5:
    container_name: cps_5
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - CPS_FQDN=localhost:7775
    command: uvicorn server-cps:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 7775:80
    volumes:
      - .:/app
    depends_on:
      - oob_db

volumes:
  mongooob:
