x-cpex-service: &cpex-service
  image: cpex
  platform: linux/x86_64
  volumes:
    - '.:/app'
  depends_on:
    - cache
  networks:
    - net

services:
# Atis OOB Services
  cert-repo:
    <<: *cpex-service
    container_name: cert-repo
    command: uvicorn cpex.prototype.stirshaken.cert_repo:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8888:80

# Experiment Runner
  experiment:
    <<: *cpex-service
    container_name: cpex-exp
    command: tail -f /dev/null
    environment:
      - DOCKER_SOCKET_PATH=${DOCKER_SOCKET_PATH:-/var/run/docker.sock}
      - HOST_APP_PATH=${HOST_APP_PATH}
    volumes:
      - '.:/app'
      - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock

  automation:
    image: cpex-automation
    container_name: cpex-automation
    command: tail -f /dev/null
    volumes:
      - './automation:/manager'
      - './docker/data/automation/.aws:/root/.aws'
      - './docker/data/automation/.ssh:/root/.ssh'

# Cache and Database
  cache:
    container_name: cpex-cache
    image: redis
    platform: linux/x86_64
    ports:
      - 6379:6379
    networks:
      - net
  
  mongo:
    container_name: cpex-mongo
    image: mongo
    platform: linux/x86_64
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - ./docker/data/mongo:/data/db
    networks:
      - net

networks:
  net:
    driver: bridge