networks:
  net:
    driver: bridge

services:
  db:
    container_name: cpex-db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - ./docker/data/mongo:/data/db
    networks:
      - net

  cert-auths:
    container_name: cert-auths
    image: cpex
    command: uvicorn cpex/servers/cert_auths:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8888:80
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - net
