networks:
  net:
    driver: bridge

services:
  db:
    container_name: cpex_db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - ./docker/data/mongo:/data/db
    networks:
      - net

  # admin:
  #   container_name: admin
  #   image: cpex
  #   command: uvicorn cpex/servers/admin:app --host 0.0.0.0 --port 80 --reload
  #   ports:
  #     - 8888:80
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - cpexdb
  #   networks:
  #     - cpexnet
