---
- name: Setup and deploy prototype
  hosts: all
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Stop Services
      tags:
        - stop_services
      command: "./prototype.sh down"
      args:
        chdir: "{{ repo_dest }}"

    - name: Start Services
      tags:
        - start_services
      command: "./prototype.sh cpex up"
      args:
        chdir: "{{ repo_dest }}"

    
