---
- name: Setup and deploy prototype
  hosts: all
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Stop Services
      tags:
        - stop_services
      command: "./prototype.sh down"
      args:
        chdir: "{{ repo_dest }}"

    - name: Start CPEX Services
      tags:
        - start_cpex
      command: "./prototype.sh down && ./prototype.sh cpex up"
      args:
        chdir: "{{ repo_dest }}"

    - name: Start ATIS Services
      tags:
        - start_atis
      command: "./prototype.sh down && ./prototype.sh atis up"
      args:
        chdir: "{{ repo_dest }}"
