---
- name: Setup and deploy prototype
  hosts: all
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Stop Services
      tags:
        - stop_services
      command: "./prototype.sh down"
      args:
        chdir: "{{ repo_dest }}"

    - name: Clear logs
      tags:
        - clear_logs
      shell: "rm -rf ./logs/*.log"
      args:
        chdir: "{{ repo_dest }}"

    - name: Start CPEX Message Stores
      tags:
        - start_ms
      command: "./prototype.sh ms up"
      args:
        chdir: "{{ repo_dest }}"
      when: "'stores' in group_names"

    - name: Start CPEX Evaluators
      tags:
        - start_ev
      command: "./prototype.sh ev up"
      args:
        chdir: "{{ repo_dest }}"
      when: "'evaluators' in group_names"

    - name: Start ATIS Services
      tags:
        - start_cps
      command: "./prototype.sh cps up"
      args:
        chdir: "{{ repo_dest }}"
