---
- name: Setup and deploy prototype
  hosts: all
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Stop Services
      tags:
        - stop_services
      command: "./scripts/apps.sh down"
      args:
        chdir: "{{ repo_dest }}"

    - name: Clear logs
      tags:
        - clear_logs
      shell: "rm -rf ./logs/*.log"
      args:
        chdir: "{{ repo_dest }}"

    - name: Start CPEX Services
      tags:
        - start_cpex
      command: "./scripts/apps.sh cpex"
      args:
        chdir: "{{ repo_dest }}"

    - name: Start ATIS Services
      tags:
        - start_atis
      command: "./scripts/apps.sh atis"
      args:
        chdir: "{{ repo_dest }}"
